import { Project } from '../types'

export const projectsEn: Project[] = [
  {
    id: "peritocalc",
    title: "PeritoCalc",
    tagline: "Automation for Court-Appointed Experts",
    shortDescription: "SaaS for labor court experts with a cost-cascading document extraction pipeline, a pattern-learning system, and native .PJC file generation for Brazil's PJe-Calc.",
    fullDescription: "SaaS platform built for court-appointed experts and technical assistants in Brazilian labor courts. The extraction engine routes every field through eight layers ordered by cost, from native PDF text up to computer vision as a last resort, logging every decision to an auditable per-layer ledger. A pattern-learning system detects when a timecard format has already been corrected repeatedly by the same expert and starts resolving that field without further AI calls. The .PJC file generator runs on pure Python 3 with no external dependencies, producing a compressed XML file ready for direct import into the official PJe-Calc software.",
    category: "Legal Automation",
    orbitRadius: 17,
    orbitSpeed: 0.15,
    orbitAngle: 0,
    color: "#a855f7",
    iconName: "Scale",
    image: "/projects/peritocalc.webp",
    geometryType: 0,
    tags: ["Next.js 15 App Router", "Claude 3.5 Sonnet Vision", ".PJC Reverse Engineering", "Supabase RLS", "Stripe Webhooks", "Standalone Python 3"],
    metrics: [
      { label: "Time Reduction", value: "92%" },
      { label: "OCR Accuracy", value: "99.4%" },
      { label: "Extraction", value: "8-Layer Cascade" },
      { label: "Export", value: "100% Native .PJC" }
    ],
    architecture: {
      frontend: "Next.js 15 (App Router) + Tailwind CSS + Radix UI + PDF.js Worker",
      backend: "Next.js Route Handlers + Supabase SSR + Python .PJC Generator",
      ai: "Claude 3.5 Sonnet (vision) for handwritten timecards and Claude Haiku (text) for typed payslips, with prompt caching and per-call cost tracking",
      database: "PostgreSQL on Supabase with Row Level Security scoped per expert",
      infra: "Vercel + Supabase South America (São Paulo)"
    },
    keyFeatures: [
      "Eight-layer, cost-ordered extraction pipeline, from native PDF text to computer vision as a last resort, with every decision logged to an auditable ledger",
      "Pattern-learning system that memorizes recurring corrections per expert and timecard format, cutting down repeated AI calls",
      "Document-type routing: handwritten timecards processed with visual reasoning, typed payslips processed as plain text",
      "Reverse-engineered the XML/ZIP export protocol used by PJe-Calc, with the binary .PJC generated by a standalone Python script"
    ]
  },
  {
    id: "atlas-educacao",
    title: "Atlas Educação",
    tagline: "Multi-School Pedagogical Intelligence",
    shortDescription: "SaaS pedagogical management portal with per-school configurable churn-risk thresholds, fully private storage, and an AI provider chain designed to never take the product down.",
    fullDescription: "Multi-school pedagogical intelligence platform used by language, robotics, coding and professional-training schools. The churn-risk engine calculates attendance thresholds, consecutive absences and grade drops with weights configurable per school, directly from the admin panel. AI-generated narrative reports are strictly optional: with no API key configured, the interface simply hides the AI buttons and manual report writing keeps working normally. When AI is enabled, a seven-provider fallback chain absorbs rate limits that apply per organization rather than per call, so importing a full class doesn't exhaust a single provider's quota.",
    category: "Education Management",
    orbitRadius: 17,
    orbitSpeed: 0.15,
    orbitAngle: Math.PI * 0.2,
    color: "#ec4899",
    iconName: "GraduationCap",
    image: "/projects/atlas-educacao.webp",
    geometryType: 1,
    tags: ["Next.js 14", "Multi-Provider AI Chain", "Supabase Auth & RLS", "@react-pdf/renderer", "Private Storage", "Recharts"],
    metrics: [
      { label: "Churn Risk", value: "Per-School Thresholds" },
      { label: "Storage", value: "100% Private" },
      { label: "PDF Generation", value: "7 Report Types" },
      { label: "AI", value: "Always Optional" }
    ],
    architecture: {
      frontend: "Next.js App Router + Tailwind CSS + shadcn/ui + Recharts",
      backend: "Next.js Route Handlers + Supabase Storage & Database",
      ai: "Fallback chain (OpenRouter, OpenAI, Groq, Mistral, SambaNova, Gemini, Cerebras) for pedagogical reports, fully toggleable without breaking the product",
      infra: "Vercel + Supabase"
    },
    keyFeatures: [
      "Churn-risk algorithm with attendance, consecutive-absence and grade-drop thresholds configurable per school, no redeploy required",
      "Every storage bucket is private by default, with access mediated through an authenticated proxy or short-lived signed URLs",
      "Seven-provider AI fallback chain to work around organization-wide rate limits during bulk imports",
      "Weekly student ranking with academic-dimension weights configurable per school"
    ],
    links: {
      demo: "https://atlas-educacao.vercel.app"
    }
  },
  {
    id: "canal-dark",
    title: "Canal Dark",
    tagline: "Desktop Video Automation Suite",
    shortDescription: "Electron desktop app that runs the full short-video production pipeline, with automatic fallback to free providers at every step and publishing that's always manual by design.",
    fullDescription: "Desktop application built with Electron, React and TypeScript that orchestrates the complete short-video pipeline: scripting, compliance checking, per-scene imagery, narration and final editing. Every step has a free provider working with zero API key required (Pollinations.ai for images, Edge TTS for narration), and automatically falls back to it if a paid provider fails. API credentials are encrypted with the operating system's own vault, and publishing to each social network is always a manual, explicit action, the app never publishes on its own.",
    category: "Content Automation",
    orbitRadius: 17,
    orbitSpeed: 0.15,
    orbitAngle: Math.PI * 0.4,
    color: "#ef4444",
    iconName: "Clapperboard",
    image: "/projects/canal-dark.webp",
    geometryType: 2,
    tags: ["Electron", "React", "TypeScript", "Free Fallback Per Step", "FFmpeg", "YouTube, TikTok & Instagram APIs"],
    metrics: [
      { label: "Video Pipeline", value: "End to End" },
      { label: "Free Providers", value: "Image + Voice, No Key" },
      { label: "Credentials", value: "Encrypted in OS Vault" },
      { label: "Publishing", value: "Always Manual, Never Automatic" }
    ],
    architecture: {
      frontend: "React + Tailwind CSS + Electron IPC Bridge (contextBridge, no Node in renderer)",
      backend: "Electron main process (Node.js) with a dedicated service per pipeline stage",
      infra: "Native FFmpeg bundled into the binary (ffmpeg-static), no separate install required"
    },
    keyFeatures: [
      "Every stage has an automatic fallback to a free, keyless provider (Pollinations.ai for images, Edge TTS for narration), reverting to it if the paid option fails",
      "API credentials encrypted with the operating system's native vault (DPAPI on Windows, Keychain on macOS, libsecret on Linux)",
      "Heuristic compliance check before assembly, explicitly documented as an aid to human review, not a replacement for it",
      "Publishing to each social network is always a manual, explicit per-platform action; the app never publishes on its own"
    ]
  },
  {
    id: "tonico-veiculos",
    title: "Tonico Veículos",
    tagline: "Dealership Platform",
    shortDescription: "High-conversion website for a pickup-truck and used-car dealership, with prices stored in cents, accent-insensitive search, and a real, event-tracked conversion funnel.",
    fullDescription: "Custom digital platform for Tonico Veículos, a dealership in Barretos, Brazil specialized in pickup trucks and used cars. Every price is stored as an integer in cents, never as a float, eliminating an entire class of rounding bugs across the catalog. Because the managed Postgres instance doesn't ship the accent-stripping extension, text normalization for search happens at the application layer on every write. Each photo stores its real width, height and a low-resolution blur placeholder, because the inventory migrated from the old site mixes 16:9, 4:3 and vertical mobile-phone aspect ratios, and the platform needs to know the real proportions before rendering a card.",
    category: "Automotive Marketplace",
    orbitRadius: 17,
    orbitSpeed: 0.15,
    orbitAngle: Math.PI * 0.6,
    color: "#f97316",
    iconName: "CarFront",
    image: "/projects/tonico-veiculos.webp",
    geometryType: 3,
    tags: ["Next.js 16", "Prisma ORM", "Tailwind CSS 4", "PostgreSQL", "JWT Auth (jose)", "Legacy Content Migration"],
    metrics: [
      { label: "Pricing", value: "Integer Cents" },
      { label: "Search", value: "Accent-Insensitive" },
      { label: "Conversion", value: "Event-Tracked Funnel" },
      { label: "Login", value: "Brute-Force Lockout" }
    ],
    architecture: {
      frontend: "Next.js 16 (App Router) with a mobile-optimized responsive layout",
      backend: "Next.js Route Handlers + Prisma ORM + JWT sessions with bcrypt",
      database: "PostgreSQL with inventory, aspect-ratio photo metadata and analytics events",
      infra: "Docker (Alpine/Debian binary target) deployed on a self-managed VPS"
    },
    keyFeatures: [
      "Vehicle price stored as an integer in cents, eliminating rounding errors in the catalog and in price-range filters",
      "Accent-insensitive search resolved at the application layer, working around the managed database's missing native extension",
      "Per-vehicle page-view and WhatsApp-click event tracking, enabling a real, not estimated, conversion funnel",
      "Account lockout after failed login attempts, with distinct owner and manager roles"
    ]
  },
  {
    id: "erp",
    title: "Nexo ERP",
    tagline: "Complete Retail Management",
    shortDescription: "Modern API-first ERP for marketplace sellers, physical stores and assisted sales, with tax compliance, logistics and a unified multichannel catalog.",
    fullDescription: "Modern, modular enterprise resource planning system built specifically for the Brazilian retail market. It unifies tax compliance (electronic invoicing), logistics and order dispatch, financial control with bank reconciliation, a unified catalog across multiple sales channels (Mercado Livre, Shopee, own store), and nine-role RBAC with full per-action audit logging. The tax-compliance layer is designed as a pluggable provider abstraction, allowing the invoice issuer to be swapped without rewriting domain rules.",
    category: "Business Management",
    orbitRadius: 17,
    orbitSpeed: 0.15,
    orbitAngle: Math.PI * 0.8,
    color: "#f59e0b",
    iconName: "Building2",
    image: "/projects/erp.webp",
    geometryType: 10,
    tags: ["NestJS + Fastify", "Next.js", "Zustand", "Prisma", "Turborepo", "9-Role RBAC", "Per-Action Audit Log"],
    metrics: [
      { label: "Architecture", value: "API-First Modular" },
      { label: "Performance", value: "Fastify Core" },
      { label: "Roles (RBAC)", value: "9 Distinct Profiles" },
      { label: "Security", value: "Untrusted Frontend" }
    ],
    architecture: {
      frontend: "Next.js (App Router) + Zustand + React Query + Tailwind",
      backend: "NestJS running on Fastify for maximum requests-per-second throughput",
      database: "PostgreSQL with partitioned schemas and composite indexes via Prisma",
      infra: "Turborepo (api/web/worker apps) with Docker Compose and Prometheus monitoring"
    },
    keyFeatures: [
      "Packages split by bounded context (tax, logistics, finance, AI), each isolated as its own module in the monorepo",
      "Explicit security posture: the frontend is treated as untrusted, with every sensitive rule validated server-side",
      "Tax-compliance layer built as a pluggable provider abstraction (issue, cancel and query invoices), with a swappable reference implementation",
      "Audit log capturing a correlation ID, IP and user agent on every sensitive action in the system"
    ]
  },
  {
    id: "meu-assistente",
    title: "Meu Assessor",
    tagline: "WhatsApp Financial Assistant",
    shortDescription: "Financial-management assistant over WhatsApp and a web dashboard, with a pure DDD core, idempotent-by-design schedulers, and AI that never writes to the database without validation.",
    fullDescription: "Financial-intelligence platform operated through WhatsApp and a web dashboard, built across eight successive phases, each one closed out with lint, typecheck, tests and documentation before moving on. The financial core treats money strictly as Decimal (never float), distributes cents exactly across installments, and never duplicates a recurrence thanks to idempotent-by-design schedulers. AI extraction follows a strict schema with prompt-injection defenses: high-confidence input becomes an automatic entry, everything else asks for confirmation, and no AI call ever writes to the database directly.",
    category: "Financial Automation",
    orbitRadius: 17,
    orbitSpeed: 0.15,
    orbitAngle: Math.PI * 1.0,
    color: "#10b981",
    iconName: "WalletCards",
    image: "/projects/meu-assistente.webp",
    geometryType: 5,
    tags: ["NestJS", "Domain-Driven Design (DDD)", "Pure TypeScript", "BullMQ", "Prisma", "Argon2id + MFA (TOTP)"],
    metrics: [
      { label: "Progress", value: "8 Phases Completed" },
      { label: "Financial Precision", value: "Decimal, Never Float" },
      { label: "Recurrences", value: "Idempotent by Design" },
      { label: "Compliance", value: "LGPD Export & Deletion" }
    ],
    architecture: {
      frontend: "Next.js + Tailwind CSS, dashboard for accounts, cards, budgets and notifications",
      backend: "NestJS (API) + a dedicated worker for queues, AI, transcription and schedulers (BullMQ)",
      domain: "Isolated pure-TypeScript domain core, decoupled from the ORM, Evolution API and AI provider",
      database: "PostgreSQL with financial Decimal types (numeric 19,4) + Redis/BullMQ + MinIO",
      infra: "Modular monolith across three processes (web/api/worker), Coolify deploy planned on a self-managed VPS"
    },
    keyFeatures: [
      "Recurrence and daily-summary schedulers idempotent by their own key, with catch-up for delays and no duplicate sends on the same day",
      "AI extraction with a strict Zod schema and prompt-injection defenses: high confidence becomes an automatic entry, everything else asks for confirmation",
      "Audio transcription never touches disk and is discarded from memory right after feeding the same command pipeline used for typed text",
      "Multi-tenant isolation tested across every phase, with PostgreSQL RLS written as defense in depth, admin TOTP MFA, and LGPD-compliant data export/deletion"
    ]
  },
  {
    id: "atendimento-ia",
    title: "Atendimento IA",
    tagline: "Omnichannel Customer Support",
    shortDescription: "Conversational support platform trained on the company's own catalog, with smart handoff to humans and a full history logged in the CRM.",
    fullDescription: "Automated customer-service ecosystem for WhatsApp and web. It lets a company spin up virtual agents that understand product questions, check availability and quotes in real time, hand off to a human agent when needed, and log every interaction to the CRM, with guardrails to limit answers to the company's own knowledge base.",
    category: "Customer Support",
    orbitRadius: 17,
    orbitSpeed: 0.15,
    orbitAngle: Math.PI * 1.2,
    color: "#8b5cf6",
    iconName: "MessagesSquare",
    image: "/projects/atendimento-ia.webp",
    geometryType: 6,
    tags: ["WhatsApp Business API", "Semantic Search", "Next.js", "Node.js", "Redis Cache", "Integrated CRM"],
    metrics: [
      { label: "Response Time", value: "< 2 seconds" },
      { label: "Automated Resolution", value: "85% of Cases" },
      { label: "Availability", value: "24/7, No Downtime" },
      { label: "Channels", value: "WhatsApp + Webchat" }
    ],
    architecture: {
      frontend: "Next.js admin panel + Tailwind + live conversation view",
      backend: "Node.js / Express with webhooks for the WhatsApp Business API",
      ai: "Semantic search over the company's knowledge base with guardrails against out-of-scope answers",
      database: "PostgreSQL storing lead history, tickets and transcripts",
      infra: "Docker container on a VPS"
    },
    keyFeatures: [
      "Human-feeling support around the clock, with support for both audio and text messages",
      "Handoff to human agents with the full conversation context preserved",
      "Automatic lead qualification capturing name, phone, interest and budget",
      "Metrics dashboard tracking average handling time, conversion rate and customer sentiment"
    ]
  },
  {
    id: "ponto-eletronico",
    title: "Ponto Eletrônico",
    tagline: "Facial Biometric Timecard",
    shortDescription: "Multi-location corporate time-tracking system with facial recognition running in its own microservice, configurable schedules and an absence-approval workflow.",
    fullDescription: "Time-and-attendance solution for companies with multiple locations. Facial recognition runs in an isolated Python microservice (FastAPI, dlib and face_recognition), matching a captured face against enrolled records with a similarity threshold configurable via environment variable. The web dashboard covers hourly and salaried employee management, work schedules (standard, 12x36 and others), break and tolerance controls, absence and justification approval, and attendance reporting.",
    category: "Computer Vision",
    orbitRadius: 17,
    orbitSpeed: 0.15,
    orbitAngle: Math.PI * 1.4,
    color: "#3b82f6",
    iconName: "ScanFace",
    image: "/projects/ponto-eletronico.webp",
    geometryType: 7,
    tags: ["Facial Recognition (dlib)", "FastAPI", "Next.js 14", "Prisma", "Docker Compose", "PostgreSQL 15"],
    metrics: [
      { label: "Biometrics", value: "Isolated Microservice" },
      { label: "Match Threshold", value: "Configurable (default 0.6)" },
      { label: "Schedules", value: "Standard, 12x36 & More" },
      { label: "Multi-Location", value: "Centralized Management" }
    ],
    architecture: {
      frontend: "Next.js 14 (App Router) + Tailwind CSS + responsive camera capture",
      backend: "Python facial-biometrics microservice (FastAPI, dlib, face_recognition) + Next.js API routes with Prisma",
      database: "PostgreSQL 15 with employee, schedule and clock-in records",
      infra: "Docker Compose orchestrating the frontend, biometrics API and database"
    },
    keyFeatures: [
      "Facial recognition in its own microservice, with dedicated detection, matching and enrollment endpoints",
      "Facial match threshold configurable via environment variable, tunable per location without a code change",
      "Support for multiple schedule types (standard, 12x36) with per-employee break and tolerance controls",
      "Absence and justification approval workflow integrated into HR attendance reports"
    ]
  },
  {
    id: "sondei",
    title: "Sondei",
    tagline: "Multi-Store Automotive Ecosystem",
    shortDescription: "Automotive marketplace with a recommendation assistant that structurally cannot hallucinate a vehicle, a fully imported national price catalog, and 443 integration tests against a real database.",
    fullDescription: "Automotive ecosystem with a distributed architecture built for nationwide expansion, starting in Barretos, Brazil. The public portal searches vehicles by distance radius against a fully imported national pricing catalog (238 brands, 2,325 models, 11,354 trims) and government geography data (27 states, 5,571 municipalities). The standout piece is the Sondei Consultant: the language layer never gets a database connection, it only extracts structured filters from the user's question, and the reply is built on top of results that already came from an application-controlled SQL query, which makes it structurally impossible for the assistant to recommend a vehicle that isn't actually in stock.",
    category: "Automotive Marketplace",
    orbitRadius: 17,
    orbitSpeed: 0.15,
    orbitAngle: Math.PI * 1.6,
    color: "#0284c7",
    iconName: "Gauge",
    image: "/projects/sondei.webp",
    geometryType: 8,
    tags: ["Turborepo Monorepo", "Next.js", "Drizzle ORM", "Two-Layer Intent Extraction", "BullMQ + Redis", "443 Tests Against Real Postgres"],
    metrics: [
      { label: "Automated Tests", value: "443 (Real Postgres)" },
      { label: "Price Catalog", value: "11,354 Trims" },
      { label: "Geography Data", value: "5,571 Municipalities" },
      { label: "Consultant", value: "Zero Hallucination by Design" }
    ],
    architecture: {
      frontend: "Next.js + Tailwind CSS with dynamic branding and colors pulled from the database (Design as Data)",
      backend: "Next.js App Router + Drizzle ORM, 18 migrations organized by domain",
      ai: "Two-layer intent extraction: deterministic rules resolve first (budget, transmission, fuel type), the model only fills in what's left and never overrides the rule on conflict",
      database: "PostgreSQL with indexed geo-spatial queries and RLS validated by per-user isolation tests",
      infra: "Docker Compose + Coolify + Cloudflare CDN + S3/MinIO"
    },
    keyFeatures: [
      "Recommendation assistant where the language layer never touches the database: it only extracts filters and writes the reply around results the application already fetched",
      "Two-layer intent extraction, with the deterministic rule always winning a budget conflict against the model, because showing a car outside a buyer's budget is the costliest mistake",
      "Runs in production with zero API keys configured; enabling an AI provider is a single environment variable, no code changes",
      "Listings processed to AVIF/WebP with EXIF stripped, and regional ad visibility scoped to the paid coverage area"
    ],
    links: {
      demo: "https://sondei.org"
    }
  },
  {
    id: "liquida-sorte",
    title: "Liquida Sorte",
    tagline: "Inventory Liquidation via Auditable Draw",
    shortDescription: "Platform for liquidating a closing store's inventory, with an append-only balance ledger, a draw that structurally can't run below the minimum, and checkout locked behind a legal-approval feature flag.",
    fullDescription: "Platform that organizes a closing store's inventory liquidation into lots, with participation through cards and an auditable draw that only runs once an internal operational minimum is reached. The customer's balance is always derived from an append-only ledger, never edited directly, and every payment webhook is idempotent. Because it's a legally sensitive product, public checkout and real draw execution sit behind feature flags that default to off in every environment, only enabled after legal, tax and payment-provider approval.",
    category: "Inventory Liquidation",
    orbitRadius: 17,
    orbitSpeed: 0.15,
    orbitAngle: Math.PI * 1.8,
    color: "#818cf8",
    iconName: "Ticket",
    image: "/projects/liquida-sorte.webp",
    geometryType: 9,
    tags: ["Turborepo Monorepo", "Next.js App Router", "Prisma", "BullMQ + Redis", "Append-Only Ledger", "Legal Feature Flags"],
    metrics: [
      { label: "Customer Balance", value: "Append-Only Ledger" },
      { label: "Draw", value: "Never Below Minimum" },
      { label: "Checkout & Draw", value: "Behind Feature Flag" },
      { label: "Deploy", value: "Manual Approval + Checklist" }
    ],
    architecture: {
      frontend: "Next.js App Router: public portal (web) and isolated backoffice (admin), separate apps in the monorepo",
      backend: "Node + BullMQ + Redis for async processes (payment, draw, notifications)",
      database: "PostgreSQL via Prisma, with a dedicated domain package for lot, ledger, card and draw rules",
      infra: "Turborepo + pnpm workspaces, CI running lint/typecheck/test/build on every PR, no automatic deploy"
    },
    keyFeatures: [
      "Customer balance always derived from an append-only ledger, never edited directly, eliminating silent value drift",
      "Draw structurally unable to run below the lot's operational minimum, with every critical admin action generating an audit trail",
      "Public checkout and real draw execution switched off by feature flag in every environment until the legal, tax and payment checklist is approved",
      "Structured logger shared across apps that never exposes a password, token, secret or national ID in plain text"
    ]
  }
]
